### ISSUE TITLE
Convert unit tests to PyTest

### ISSUE THREAD

**Issue by sheldonkwoodward** [sheldonkwoodward/modrc#22]
**Is your enhancement request related to a problem? Please describe.**
Currently, Python's built in test suite unittest is being used to test the helper library. This library does not scale well and perform equally across python versions.

**Describe the solution you'd like**
These tests should be converted to PyTest tests with fixtures and a more scalable setup.

**Implementation steps**
 - [ ] Auto convert for PyTest compatibility
 - [ ] Write fixtures for common test setups
 - [ ] Cleanup/re-write tests

**Additional context**
None
