### ISSUE TITLE
Pre/post-compile hooks

### ISSUE THREAD

**Issue by sheldonkwoodward** [sheldonkwoodward/modrc#33]
**Is your feature request related to a problem? Please describe.**
After compiling a file such as .zshrc, there is no way to automatically run an action after it.

**Describe the solution you'd like**
Add hooks that can run a script or predefined action before or after a file is compiled.

**Implementation steps**
 - [ ] Add file.yml for configuration
 - [ ] Pre-compile runner
 - [ ] Post-compile runner

**Additional context**
None
