### ISSUE TITLE
Add header comments to all files

### ISSUE THREAD

**Issue by sheldonkwoodward** [sheldonkwoodward/modrc#40]
**Is your enhancement request related to a problem? Please describe.**
There are currently no header comments for each file.

**Describe the solution you'd like**
Define a standard header comment style and implement it in all files.

**Implementation steps**
 - [ ] Define header comment style
 - [ ] Add headers to all files
 - [ ] GitHub workflow to check for header files

**Additional context**
None
